#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="blotter")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::AppSystem.Properties.Settings.Default.blotterConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_biometric_login")]
		public ISingleResult<sp_biometric_loginResult> sp_biometric_login()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_biometric_loginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_checkUsername")]
		public ISingleResult<sp_checkUsernameResult> sp_checkUsername([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(MAX)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<sp_checkUsernameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_deleteUser")]
		public int sp_deleteUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(1)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getUsertype")]
		public ISingleResult<sp_getUsertypeResult> sp_getUsertype([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(MAX)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<sp_getUsertypeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[sp_insertLog()]")]
		public int sp_insertLog__([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID1", DbType="VarChar(MAX)")] string iD1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID2", DbType="VarChar(MAX)")] string iD2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID3", DbType="VarChar(MAX)")] string iD3)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD1, iD2, iD3);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_login")]
		public ISingleResult<sp_loginResult> sp_login([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID1", DbType="VarChar(MAX)")] string iD1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID2", DbType="VarChar(MAX)")] string iD2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD1, iD2);
			return ((ISingleResult<sp_loginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_selectLogs")]
		public ISingleResult<sp_selectLogsResult> sp_selectLogs([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dat1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> dat2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dat1, dat2);
			return ((ISingleResult<sp_selectLogsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_selectLevel")]
		public ISingleResult<sp_selectLevelResult> sp_selectLevel()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_selectLevelResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GradeSELECT")]
		public ISingleResult<GradeSELECTResult> GradeSELECT()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GradeSELECTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SectionSELECT")]
		public ISingleResult<SectionSELECTResult> SectionSELECT()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SectionSELECTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AccountSelectByBIOMETRICS")]
		public ISingleResult<AccountSelectByBIOMETRICSResult> AccountSelectByBIOMETRICS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string biometrics)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), biometrics);
			return ((ISingleResult<AccountSelectByBIOMETRICSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AccountSelectByRFID")]
		public ISingleResult<AccountSelectByRFIDResult> AccountSelectByRFID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RFID", DbType="VarChar(50)")] string rFID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rFID);
			return ((ISingleResult<AccountSelectByRFIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckDTRifLOGGED")]
		public ISingleResult<CheckDTRifLOGGEDResult> CheckDTRifLOGGED([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecID", DbType="VarChar(20)")] string recID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recID);
			return ((ISingleResult<CheckDTRifLOGGEDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DtrINSERT")]
		public int DtrINSERT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountID", DbType="VarChar(50)")] string accountID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remark", DbType="VarChar(50)")] string remark)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountID, remark);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DailyTimeRecordSelectAll")]
		public ISingleResult<DailyTimeRecordSelectAllResult> DailyTimeRecordSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DailyTimeRecordSelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lookupRequest")]
		public ISingleResult<lookupRequestResult> lookupRequest([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Account", DbType="VarChar(50)")] string account)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account);
			return ((ISingleResult<lookupRequestResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getRequest")]
		public ISingleResult<getRequestResult> getRequest()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getRequestResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_InsertUser")]
		public int sp_InsertUser(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="VarChar(100)")] string firstname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Middlename", DbType="VarChar(100)")] string middlename, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="VarChar(100)")] string lastname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level_cn", DbType="VarChar(100)")] string level_cn, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(100)")] string username, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(100)")] string password, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary biometrics, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RFID", DbType="VarChar(100)")] string rFID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AVATAR", DbType="VarBinary(MAX)")] System.Data.Linq.Binary aVATAR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LRN", DbType="VarChar(100)")] string lRN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Grade", DbType="VarChar(100)")] string grade, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECTION_", DbType="VarChar(100)")] string sECTION_, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(100)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remarks", DbType="VarChar(100)")] string remarks, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNo", DbType="VarChar(100)")] string phoneNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BirthDate", DbType="VarChar(100)")] string birthDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Strand", DbType="VarChar(100)")] string strand, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SchoolYear", DbType="VarChar(100)")] string schoolYear, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GuardianName", DbType="VarChar(100)")] string guardianName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Schedule", DbType="VarChar(100)")] string schedule, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adviser", DbType="VarChar(100)")] string adviser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstname, middlename, lastname, email, level_cn, username, password, biometrics, rFID, aVATAR, lRN, grade, sECTION_, status, remarks, phoneNo, birthDate, strand, schoolYear, guardianName, schedule, adviser);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UpdateUser")]
		public int sp_UpdateUser(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Firstname", DbType="VarChar(100)")] string firstname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Middlename", DbType="VarChar(100)")] string middlename, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lastname", DbType="VarChar(100)")] string lastname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level_cn", DbType="VarChar(100)")] string level_cn, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(100)")] string username, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(100)")] string password, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary biometrics, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RFID", DbType="VarChar(100)")] string rFID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AVATAR", DbType="VarBinary(MAX)")] System.Data.Linq.Binary aVATAR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LRN", DbType="VarChar(100)")] string lRN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Grade", DbType="VarChar(100)")] string grade, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SECTION_", DbType="VarChar(100)")] string sECTION_, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(100)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Remarks", DbType="VarChar(100)")] string remarks, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneNo", DbType="VarChar(100)")] string phoneNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecID", DbType="VarChar(100)")] string recID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Schedule", DbType="VarChar(100)")] string schedule, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Guardian", DbType="VarChar(100)")] string guardian, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adviser", DbType="VarChar(100)")] string adviser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), firstname, middlename, lastname, email, level_cn, username, password, biometrics, rFID, aVATAR, lRN, grade, sECTION_, status, remarks, phoneNo, recID, schedule, guardian, adviser);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AccountSelectByID")]
		public ISingleResult<AccountSelectByIDResult> AccountSelectByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecID", DbType="VarChar(50)")] string recID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recID);
			return ((ISingleResult<AccountSelectByIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_AccountSELECT")]
		public ISingleResult<sp_AccountSELECTResult> sp_AccountSELECT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="VarChar(MAX)")] string iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<sp_AccountSELECTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getAdviser")]
		public ISingleResult<getAdviserResult> getAdviser()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getAdviserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getReport")]
		public ISingleResult<getReportResult> getReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateCreated", DbType="VarChar(50)")] string dateCreated, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Grade", DbType="VarChar(50)")] string grade, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Section_", DbType="VarChar(50)")] string section_, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adviser_", DbType="VarChar(50)")] string adviser_)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateCreated, grade, section_, adviser_);
			return ((ISingleResult<getReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getSchedule")]
		public ISingleResult<getScheduleResult> getSchedule([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string cn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cn);
			return ((ISingleResult<getScheduleResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DailyTimeRecordSELCT")]
		public ISingleResult<DailyTimeRecordSELCTResult> DailyTimeRecordSELCT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountID", DbType="VarChar(50)")] string accountID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountID);
			return ((ISingleResult<DailyTimeRecordSELCTResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_biometric_loginResult
	{
		
		private int _cn;
		
		private string _fullname;
		
		private System.Nullable<int> _level_cn;
		
		private System.Data.Linq.Binary _biometrics;
		
		public sp_biometric_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="VarChar(764) NOT NULL", CanBeNull=false)]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this._fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_level_cn", DbType="Int")]
		public System.Nullable<int> level_cn
		{
			get
			{
				return this._level_cn;
			}
			set
			{
				if ((this._level_cn != value))
				{
					this._level_cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_biometrics", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary biometrics
		{
			get
			{
				return this._biometrics;
			}
			set
			{
				if ((this._biometrics != value))
				{
					this._biometrics = value;
				}
			}
		}
	}
	
	public partial class sp_checkUsernameResult
	{
		
		private int _cn;
		
		public sp_checkUsernameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
	}
	
	public partial class sp_getUsertypeResult
	{
		
		private int _cn;
		
		private string _Rank;
		
		private string _Remark;
		
		public sp_getUsertypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="VarChar(254)")]
		public string Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(254)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
	}
	
	public partial class sp_loginResult
	{
		
		private int _cn;
		
		private string _fullname;
		
		private System.Nullable<int> _Level_cn;
		
		public sp_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="VarChar(764) NOT NULL", CanBeNull=false)]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this._fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Level_cn", DbType="Int")]
		public System.Nullable<int> Level_cn
		{
			get
			{
				return this._Level_cn;
			}
			set
			{
				if ((this._Level_cn != value))
				{
					this._Level_cn = value;
				}
			}
		}
	}
	
	public partial class sp_selectLogsResult
	{
		
		private int _cn;
		
		private string _ActionName;
		
		private string _ByName;
		
		private string _Modules;
		
		private System.Nullable<System.DateTime> _Date;
		
		public sp_selectLogsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionName", DbType="VarChar(254)")]
		public string ActionName
		{
			get
			{
				return this._ActionName;
			}
			set
			{
				if ((this._ActionName != value))
				{
					this._ActionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByName", DbType="VarChar(100)")]
		public string ByName
		{
			get
			{
				return this._ByName;
			}
			set
			{
				if ((this._ByName != value))
				{
					this._ByName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modules", DbType="VarChar(254)")]
		public string Modules
		{
			get
			{
				return this._Modules;
			}
			set
			{
				if ((this._Modules != value))
				{
					this._Modules = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	public partial class sp_selectLevelResult
	{
		
		private int _cn;
		
		private string _Rank;
		
		private string _Remark;
		
		public sp_selectLevelResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="VarChar(254)")]
		public string Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="VarChar(254)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
	}
	
	public partial class GradeSELECTResult
	{
		
		private int _RecID;
		
		private string _Grade;
		
		private System.Nullable<int> _Remark;
		
		public GradeSELECTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecID", DbType="Int NOT NULL")]
		public int RecID
		{
			get
			{
				return this._RecID;
			}
			set
			{
				if ((this._RecID != value))
				{
					this._RecID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="VarChar(100)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="Int")]
		public System.Nullable<int> Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
	}
	
	public partial class SectionSELECTResult
	{
		
		private int _RecID;
		
		private string _Section;
		
		private System.Nullable<int> _Remark;
		
		public SectionSELECTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecID", DbType="Int NOT NULL")]
		public int RecID
		{
			get
			{
				return this._RecID;
			}
			set
			{
				if ((this._RecID != value))
				{
					this._RecID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="VarChar(100)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this._Section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="Int")]
		public System.Nullable<int> Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
	}
	
	public partial class AccountSelectByBIOMETRICSResult
	{
		
		private int _cn;
		
		private System.Data.Linq.Binary _AVATAR;
		
		private string _AccountName;
		
		private string _LRN;
		
		private string _GradeSection_;
		
		private string _PhoneNo;
		
		public AccountSelectByBIOMETRICSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVATAR", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary AVATAR
		{
			get
			{
				return this._AVATAR;
			}
			set
			{
				if ((this._AVATAR != value))
				{
					this._AVATAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="VarChar(765)")]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this._AccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LRN", DbType="VarChar(20)")]
		public string LRN
		{
			get
			{
				return this._LRN;
			}
			set
			{
				if ((this._LRN != value))
				{
					this._LRN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeSection_", DbType="VarChar(201)")]
		public string GradeSection_
		{
			get
			{
				return this._GradeSection_;
			}
			set
			{
				if ((this._GradeSection_ != value))
				{
					this._GradeSection_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="VarChar(50)")]
		public string PhoneNo
		{
			get
			{
				return this._PhoneNo;
			}
			set
			{
				if ((this._PhoneNo != value))
				{
					this._PhoneNo = value;
				}
			}
		}
	}
	
	public partial class AccountSelectByRFIDResult
	{
		
		private int _cn;
		
		private System.Data.Linq.Binary _AVATAR;
		
		private string _AccountName;
		
		private string _LRN;
		
		private string _GradeSection_;
		
		private string _PhoneNo;
		
		public AccountSelectByRFIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVATAR", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary AVATAR
		{
			get
			{
				return this._AVATAR;
			}
			set
			{
				if ((this._AVATAR != value))
				{
					this._AVATAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="VarChar(765)")]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this._AccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LRN", DbType="VarChar(20)")]
		public string LRN
		{
			get
			{
				return this._LRN;
			}
			set
			{
				if ((this._LRN != value))
				{
					this._LRN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeSection_", DbType="VarChar(201)")]
		public string GradeSection_
		{
			get
			{
				return this._GradeSection_;
			}
			set
			{
				if ((this._GradeSection_ != value))
				{
					this._GradeSection_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="VarChar(50)")]
		public string PhoneNo
		{
			get
			{
				return this._PhoneNo;
			}
			set
			{
				if ((this._PhoneNo != value))
				{
					this._PhoneNo = value;
				}
			}
		}
	}
	
	public partial class CheckDTRifLOGGEDResult
	{
		
		private System.Nullable<int> _c;
		
		public CheckDTRifLOGGEDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c", DbType="Int")]
		public System.Nullable<int> c
		{
			get
			{
				return this._c;
			}
			set
			{
				if ((this._c != value))
				{
					this._c = value;
				}
			}
		}
	}
	
	public partial class DailyTimeRecordSelectAllResult
	{
		
		private int _RecID;
		
		private string _AccountName;
		
		private string _TimeIN;
		
		private string _TimeOUT;
		
		private System.Nullable<decimal> _Total;
		
		private string _RowRemark;
		
		private string _DateCreated;
		
		public DailyTimeRecordSelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecID", DbType="Int NOT NULL")]
		public int RecID
		{
			get
			{
				return this._RecID;
			}
			set
			{
				if ((this._RecID != value))
				{
					this._RecID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="VarChar(765)")]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this._AccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeIN", DbType="VarChar(7)")]
		public string TimeIN
		{
			get
			{
				return this._TimeIN;
			}
			set
			{
				if ((this._TimeIN != value))
				{
					this._TimeIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeOUT", DbType="VarChar(7)")]
		public string TimeOUT
		{
			get
			{
				return this._TimeOUT;
			}
			set
			{
				if ((this._TimeOUT != value))
				{
					this._TimeOUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowRemark", DbType="VarChar(100)")]
		public string RowRemark
		{
			get
			{
				return this._RowRemark;
			}
			set
			{
				if ((this._RowRemark != value))
				{
					this._RowRemark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="NVarChar(4000)")]
		public string DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
	}
	
	public partial class lookupRequestResult
	{
		
		private System.Nullable<int> _c;
		
		public lookupRequestResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c", DbType="Int")]
		public System.Nullable<int> c
		{
			get
			{
				return this._c;
			}
			set
			{
				if ((this._c != value))
				{
					this._c = value;
				}
			}
		}
	}
	
	public partial class getRequestResult
	{
		
		private int _RecID;
		
		private string _Name;
		
		private string _For;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private string _Approve;
		
		private string _Note;
		
		public getRequestResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecID", DbType="Int NOT NULL")]
		public int RecID
		{
			get
			{
				return this._RecID;
			}
			set
			{
				if ((this._RecID != value))
				{
					this._RecID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(765)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[For]", Storage="_For", DbType="VarChar(100)")]
		public string For
		{
			get
			{
				return this._For;
			}
			set
			{
				if ((this._For != value))
				{
					this._For = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approve", DbType="VarChar(100)")]
		public string Approve
		{
			get
			{
				return this._Approve;
			}
			set
			{
				if ((this._Approve != value))
				{
					this._Approve = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="VarChar(150)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
	}
	
	public partial class AccountSelectByIDResult
	{
		
		private int _cn;
		
		private string _Firstname;
		
		private string _Middlename;
		
		private string _Lastname;
		
		private string _Email;
		
		private System.Nullable<int> _Level_cn;
		
		private string _Username;
		
		private string _Password;
		
		private System.Data.Linq.Binary _biometrics;
		
		private string _RFID;
		
		private System.Data.Linq.Binary _AVATAR;
		
		private string _LRN;
		
		private System.Nullable<int> _Grade;
		
		private System.Nullable<int> _Section;
		
		private string _Status;
		
		private string _Remarks;
		
		private string _PhoneNo;
		
		private System.Nullable<System.DateTime> _BirrthDate;
		
		private string _Strand;
		
		private string _SchoolYear;
		
		private string _GuardianName;
		
		private string _Schedule;
		
		private string _RowRemark;
		
		private string _Adviser;
		
		private string _GradeName;
		
		private string _Section_;
		
		public AccountSelectByIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(254)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middlename", DbType="VarChar(254)")]
		public string Middlename
		{
			get
			{
				return this._Middlename;
			}
			set
			{
				if ((this._Middlename != value))
				{
					this._Middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="VarChar(254)")]
		public string Lastname
		{
			get
			{
				return this._Lastname;
			}
			set
			{
				if ((this._Lastname != value))
				{
					this._Lastname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(254)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Level_cn", DbType="Int")]
		public System.Nullable<int> Level_cn
		{
			get
			{
				return this._Level_cn;
			}
			set
			{
				if ((this._Level_cn != value))
				{
					this._Level_cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(254)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(254)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_biometrics", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary biometrics
		{
			get
			{
				return this._biometrics;
			}
			set
			{
				if ((this._biometrics != value))
				{
					this._biometrics = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFID", DbType="VarChar(100)")]
		public string RFID
		{
			get
			{
				return this._RFID;
			}
			set
			{
				if ((this._RFID != value))
				{
					this._RFID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVATAR", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary AVATAR
		{
			get
			{
				return this._AVATAR;
			}
			set
			{
				if ((this._AVATAR != value))
				{
					this._AVATAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LRN", DbType="VarChar(20)")]
		public string LRN
		{
			get
			{
				return this._LRN;
			}
			set
			{
				if ((this._LRN != value))
				{
					this._LRN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="Int")]
		public System.Nullable<int> Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="Int")]
		public System.Nullable<int> Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this._Section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(20)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="VarChar(50)")]
		public string PhoneNo
		{
			get
			{
				return this._PhoneNo;
			}
			set
			{
				if ((this._PhoneNo != value))
				{
					this._PhoneNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirrthDate", DbType="DateTime2")]
		public System.Nullable<System.DateTime> BirrthDate
		{
			get
			{
				return this._BirrthDate;
			}
			set
			{
				if ((this._BirrthDate != value))
				{
					this._BirrthDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Strand", DbType="VarChar(100)")]
		public string Strand
		{
			get
			{
				return this._Strand;
			}
			set
			{
				if ((this._Strand != value))
				{
					this._Strand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolYear", DbType="VarChar(100)")]
		public string SchoolYear
		{
			get
			{
				return this._SchoolYear;
			}
			set
			{
				if ((this._SchoolYear != value))
				{
					this._SchoolYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuardianName", DbType="VarChar(100)")]
		public string GuardianName
		{
			get
			{
				return this._GuardianName;
			}
			set
			{
				if ((this._GuardianName != value))
				{
					this._GuardianName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schedule", DbType="VarChar(100)")]
		public string Schedule
		{
			get
			{
				return this._Schedule;
			}
			set
			{
				if ((this._Schedule != value))
				{
					this._Schedule = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowRemark", DbType="VarChar(100)")]
		public string RowRemark
		{
			get
			{
				return this._RowRemark;
			}
			set
			{
				if ((this._RowRemark != value))
				{
					this._RowRemark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adviser", DbType="VarChar(100)")]
		public string Adviser
		{
			get
			{
				return this._Adviser;
			}
			set
			{
				if ((this._Adviser != value))
				{
					this._Adviser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeName", DbType="VarChar(100)")]
		public string GradeName
		{
			get
			{
				return this._GradeName;
			}
			set
			{
				if ((this._GradeName != value))
				{
					this._GradeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section_", DbType="VarChar(100)")]
		public string Section_
		{
			get
			{
				return this._Section_;
			}
			set
			{
				if ((this._Section_ != value))
				{
					this._Section_ = value;
				}
			}
		}
	}
	
	public partial class sp_AccountSELECTResult
	{
		
		private int _cn;
		
		private string _fullname;
		
		private string _Username;
		
		private System.Nullable<int> _Level_cn;
		
		private string _Rank;
		
		private string _Status;
		
		private string _Remarks;
		
		private string _Grade;
		
		private string _Section;
		
		private string _Schedule;
		
		private string _Adviser;
		
		public sp_AccountSELECTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cn", DbType="Int NOT NULL")]
		public int cn
		{
			get
			{
				return this._cn;
			}
			set
			{
				if ((this._cn != value))
				{
					this._cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="VarChar(764) NOT NULL", CanBeNull=false)]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this._fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(254)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Level_cn", DbType="Int")]
		public System.Nullable<int> Level_cn
		{
			get
			{
				return this._Level_cn;
			}
			set
			{
				if ((this._Level_cn != value))
				{
					this._Level_cn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="VarChar(254)")]
		public string Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(20)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="VarChar(100)")]
		public string Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="VarChar(100)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this._Section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schedule", DbType="VarChar(100)")]
		public string Schedule
		{
			get
			{
				return this._Schedule;
			}
			set
			{
				if ((this._Schedule != value))
				{
					this._Schedule = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adviser", DbType="VarChar(100)")]
		public string Adviser
		{
			get
			{
				return this._Adviser;
			}
			set
			{
				if ((this._Adviser != value))
				{
					this._Adviser = value;
				}
			}
		}
	}
	
	public partial class getAdviserResult
	{
		
		private string _Adviser;
		
		public getAdviserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adviser", DbType="VarChar(100)")]
		public string Adviser
		{
			get
			{
				return this._Adviser;
			}
			set
			{
				if ((this._Adviser != value))
				{
					this._Adviser = value;
				}
			}
		}
	}
	
	public partial class getReportResult
	{
		
		private int _RecID;
		
		private string _AccountName;
		
		private string _TimeIN;
		
		private string _TimeOUT;
		
		private System.Nullable<decimal> _Total;
		
		private string _RowRemark;
		
		private string _DateCreated;
		
		public getReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecID", DbType="Int NOT NULL")]
		public int RecID
		{
			get
			{
				return this._RecID;
			}
			set
			{
				if ((this._RecID != value))
				{
					this._RecID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="VarChar(765)")]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this._AccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeIN", DbType="VarChar(7)")]
		public string TimeIN
		{
			get
			{
				return this._TimeIN;
			}
			set
			{
				if ((this._TimeIN != value))
				{
					this._TimeIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeOUT", DbType="VarChar(7)")]
		public string TimeOUT
		{
			get
			{
				return this._TimeOUT;
			}
			set
			{
				if ((this._TimeOUT != value))
				{
					this._TimeOUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowRemark", DbType="VarChar(100)")]
		public string RowRemark
		{
			get
			{
				return this._RowRemark;
			}
			set
			{
				if ((this._RowRemark != value))
				{
					this._RowRemark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="NVarChar(4000)")]
		public string DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
	}
	
	public partial class getScheduleResult
	{
		
		private string _Column1;
		
		public getScheduleResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="VarChar(102) NOT NULL", CanBeNull=false)]
		public string Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class DailyTimeRecordSELCTResult
	{
		
		private int _RecID;
		
		private string _AccountName;
		
		private string _TimeIN;
		
		private string _TimeOUT;
		
		private System.Nullable<decimal> _Total;
		
		private string _RowRemark;
		
		private string _DateCreated;
		
		public DailyTimeRecordSELCTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecID", DbType="Int NOT NULL")]
		public int RecID
		{
			get
			{
				return this._RecID;
			}
			set
			{
				if ((this._RecID != value))
				{
					this._RecID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="VarChar(765)")]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this._AccountName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeIN", DbType="VarChar(7)")]
		public string TimeIN
		{
			get
			{
				return this._TimeIN;
			}
			set
			{
				if ((this._TimeIN != value))
				{
					this._TimeIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeOUT", DbType="VarChar(7)")]
		public string TimeOUT
		{
			get
			{
				return this._TimeOUT;
			}
			set
			{
				if ((this._TimeOUT != value))
				{
					this._TimeOUT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowRemark", DbType="VarChar(100)")]
		public string RowRemark
		{
			get
			{
				return this._RowRemark;
			}
			set
			{
				if ((this._RowRemark != value))
				{
					this._RowRemark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="NVarChar(4000)")]
		public string DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this._DateCreated = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
